Description: IAM Roles for Jonathan's AWS Account

Resources:
  BuildAgentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'BuildAgent'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - autoscaling:*
              - application-autoscaling:*
              - cloudwatch:*
              - events:*
              - ec2:*
              - elasticache:*
              - elasticloadbalancing:*
              - route53:*
              - s3:*
              - glue:*
              - lambda:*
              - apigateway:*
              - sns:*
              - ecr:*
              - "cloudfront:*"
              - eks:*
              - "ecs:*"
              - "sqs:*"
              - "rds:*"
              - "logs:*"
              - "kinesis:*"
              - "kms:*"
              - "firehose:*"
              - "dynamodb:*"
              - "es:*"
              - "ssm:*"
              - "waf:*"
              - "waf-regional:*"
              - "secretsmanager:*"
              - "states:*"
              - "acm:*"
            Resource: "*"
          - Effect: Allow
            Action: 
              - "cloudformation:CancelUpdateStack"
              - "cloudformation:CreateStack"
              - "cloudformation:Describe*"
              - "cloudformation:EstimateTemplateCost"
              - "cloudformation:GetTemplate"
              - "cloudformation:GetTemplateSummary"
              - "cloudformation:List*"
              - "cloudformation:UpdateStack"
              - "cloudformation:ValidateTemplate"
              - "cloudformation:SetStackPolicy"
              - "cloudformation:*ChangeSet"
              - "cloudformation:DeleteStack"
            Resource: '*'
          - Effect: Allow
            Action: 
              - "iam:AddRoleToInstanceProfile"
              - "iam:CreateInstanceProfile"
              - "iam:CreateRole"
              - "iam:DeleteInstanceProfile"
              - "iam:DeleteRolePolicy"
              - "iam:DeleteRole"
              - "iam:GetRole"
              - "iam:GetRolePolicy"
              - "iam:ListInstanceProfilesForRole"
              - "iam:ListRolePolicies"
              - "iam:PassRole"
              - "iam:PutRolePolicy"
              - "iam:RemoveRoleFromInstanceProfile"
              - "iam:UpdateAssumeRolePolicy"
              - "iam:GetInstanceProfile"
              - "iam:DetachRolePolicy"
              - "iam:CreatePolicy"
              - "iam:AttachRolePolicy"
              - "iam:GetPolicy"
              - "iam:ListPolicyVersions"
              - "iam:CreateGroup"
              - "iam:DeleteGroup"
              - "iam:AttachGroupPolicy"
              - "iam:DetachGroupPolicy"
              - "iam:CreatePolicyVersion"
              - "iam:DeletePolicyVersion"
              - "iam:TagRole"
              - "iam:UntagRole"
            Resource: '*'
