Description: ECR for Jonathan's AWS Account

Parameters:
  EcrRepositoryName:
    Type: String
    Default: 'jonathans'

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties: 
      LifecyclePolicy: 
        LifecyclePolicyText: >
          {
            "rules": [
                {
                    "rulePriority": 1,
                    "description": "Keep only one untagged image, expire all others",
                    "selection": {
                        "tagStatus": "untagged",
                        "countType": "imageCountMoreThan",
                        "countNumber": 1
                    },
                    "action": {
                        "type": "expire"
                    }
                }
            ]
          }
      RepositoryName: !Ref EcrRepositoryName

